server:
  port: 8080
  servlet:
    # Each micro-service has its own path
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: password
  jpa:
    hibernate:
      # Hibernate create the table for me
      # Thuc te phai tao ra script SQL cho tem dev-op tao databse
      ddl-auto: update
    show-sql: true
