package com.devteria.identityservice.service;

import com.devteria.identityservice.dto.request.UserCreationRequest;
import com.devteria.identityservice.dto.request.UserUpdateRequest;
import com.devteria.identityservice.dto.response.UserResponse;
import com.devteria.identityservice.entity.User;
import com.devteria.identityservice.enums.Role;
import com.devteria.identityservice.exception.AppException;
import com.devteria.identityservice.exception.ErrorCode;
import com.devteria.identityservice.mapper.UserMapper;
import com.devteria.identityservice.repository.UserRepository;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.prepost.PostAuthorize;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
@Slf4j
public class UserService {
    // @Autowire is not the best-practice when doing DI
    // use constructor injection instead using @RequiredArgsConstructor
    // constructor is generated by lombok
     UserRepository userRepository;
     UserMapper userMapper;
     // @Bean khai bao o SecurityConfig
     PasswordEncoder passwordEncoder;

    public UserResponse createUser(UserCreationRequest request){
        // kiem tra user already exist
        if (userRepository.existsByUsername(request.getUsername()))
            throw new AppException(ErrorCode.USER_EXISTED);

        User user = userMapper.toUser(request);
        // hash password
        // da inject bean passwordEncoder tu config roi nen khong can new nua
//        PasswordEncoder passwordEncoder = new BCryptPasswordEncoder(10);
        user.setPassword(passwordEncoder.encode(request.getPassword()));

        // set role cho user default la 'USER'
        HashSet<String> roles = new HashSet<>();
        roles.add(Role.USER.name());

        user.setRoles(roles);

        // persist xuống database
        return userMapper.toUserResponse(userRepository.save(user));
    }

    // lấy info based on thong tin user lưu trong token
    // khong can truyen vao id
    public UserResponse getMyInfo() {
        var context = SecurityContextHolder.getContext();
        String name = context.getAuthentication().getName();

        User user = userRepository.findByUsername(name).orElseThrow(
          () -> new AppException(ErrorCode.USER_NOT_EXISTED)
        );

        return userMapper.toUserResponse(user);
    }

    public UserResponse updateUser(String userId, UserUpdateRequest request) {
        // getUser() is defined below in the same file
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not founddd"));
        userMapper.updateUser(user, request);

        // map từ User -> UserResponse DTO tra ve cho controller
        return userMapper.toUserResponse(userRepository.save(user));
    }

    public void deleteUser(String userId){
        userRepository.deleteById(userId);
    }

    // authorization base on method
    @PreAuthorize("hasRole('ADMIN')")
    public List<UserResponse> getUsers(){
        log.info("UserService >> getUsers()");
//        return userRepository.findAll();
        return userRepository.findAll().stream()
                 .map(userMapper::toUserResponse).toList();
    }

    // check if user tra ve co dung la user dang dang nhap (trong token) moi cho tra ve ket qua
    // user chi co the lay thong tin cua chinh minh
    // khong lay duoc thong tin cua cac users khác trong he thong
    @PostAuthorize("returnObject.username == authentication.name")
    public UserResponse getUser(String id){
        log.info("UserService >> getUser() by Id");
        return userMapper.toUserResponse(userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("User not founddd")));
    }
}
